import { Product, DailyStats, Transaction, Expense } from './types';

export const THEME = {
  primary: '#0A4CFF',
  secondary: '#1638D6',
  accent: '#00C2FF',
  darkBg: '#020A1C',
  glassBorder: 'rgba(255,255,255,0.1)',
  textSecondary: 'rgba(255,255,255,0.6)',
};

export const TRANSLATIONS: any = {
  'English': {
    home: 'Home',
    trends: 'Trends',
    forecast: 'Forecast',
    settings: 'Settings',
    todaysSales: "Today's Sales",
    orders: 'Orders',
    visits: 'Visits',
    avgBill: 'Avg Bill',
    expenses: 'Expenses',
    profit: 'Profit',
    topMovers: 'Top Movers',
    needsAttention: 'Needs Attention',
    addSale: 'Add Sale',
    addExpense: 'Add Expense',
    newItem: 'New Item',
    seeAll: 'See all',
    welcome: 'Welcome back, Shopkeeper',
    recentActivity: "Today's Activity",
    revenueHistory: "Revenue History",
    categoryBreakdown: "Category Breakdown",
    peakHours: "Peak Hours",
    aiForecast: "AI Forecast",
    poweredBy: "Powered by Gemini",
    predictedProfit: "Projected Profit",
    smartAlerts: "Smart Inventory Alerts",
    language: "Language",
    lowDataMode: "Low Data Mode",
    backupData: "Backup Data",
    clearData: "Clear Today's Data",
    factoryReset: "Factory Reset (Monthly)",
    shareBill: "Share Bill",
    completeSale: "Complete Sale"
  },
  'Hindi (हिंदी)': {
    home: 'होम',
    trends: 'रुझान',
    forecast: 'अनुमान',
    settings: 'सेटिंग्स',
    todaysSales: 'आज की बिक्री',
    orders: 'ऑर्डर',
    visits: 'ग्राहक',
    avgBill: 'औसत बिल',
    expenses: 'खर्च',
    profit: 'मुनाफा',
    topMovers: 'सबसे ज्यादा बिकने वाले',
    needsAttention: 'ध्यान दें',
    addSale: 'बिक्री जोड़ें',
    addExpense: 'खर्च जोड़ें',
    newItem: 'नया आइटम',
    seeAll: 'सभी देखें',
    welcome: 'स्वागत है, दुकानदार',
    recentActivity: "आज की गतिविधियां",
    revenueHistory: "बिक्री इतिहास",
    categoryBreakdown: "श्रेणी विश्लेषण",
    peakHours: "व्यस्त समय",
    aiForecast: "AI अनुमान",
    poweredBy: "Gemini द्वारा संचालित",
    predictedProfit: "अनुमानित मुनाफा",
    smartAlerts: "स्टॉक अलर्ट",
    language: "भाषा",
    lowDataMode: "लो डेटा मोड",
    backupData: "डेटा बैकअप",
    clearData: "आज का डेटा साफ़ करें",
    factoryReset: "फैक्ट्री रीसेट (मासिक)",
    shareBill: "बिल शेयर करें",
    completeSale: "बिक्री पूरी करें"
  },
  'Gujarati (ગુજરાતી)': {
    home: 'હોમ',
    trends: 'ટ્રેન્ડ્સ',
    forecast: 'આગાહી',
    settings: 'સેટિંગ્સ',
    todaysSales: 'આજનું વેચાણ',
    orders: 'ઓર્ડર',
    visits: 'મુલાકાતો',
    avgBill: 'સરેરાશ બિલ',
    expenses: 'ખર્ચ',
    profit: 'નફો',
    topMovers: 'વધુ વેચાતી વસ્તુઓ',
    needsAttention: 'ધ્યાન આપો',
    addSale: 'વેચાણ ઉમેરો',
    addExpense: 'ખર્ચ ઉમેરો',
    newItem: 'નવી વસ્તુ',
    seeAll: 'બધું જુઓ',
    welcome: 'સ્વાગત છે, વેપારી',
    recentActivity: "આજની પ્રવૃત્તિ",
    revenueHistory: "આવકનો ઇતિહાસ",
    categoryBreakdown: "વર્ગીકરણ",
    peakHours: "વ્યસ્ત કલાકો",
    aiForecast: "AI આગાહી",
    poweredBy: "Gemini દ્વારા સંચાલિત",
    predictedProfit: "અંદાજિત નફો",
    smartAlerts: "સ્ટોક એલર્ટ્સ",
    language: "ભાષા",
    lowDataMode: "લો ડેટા મોડ",
    backupData: "ડેટા બેકઅપ",
    clearData: "આજનો ડેટા સાફ કરો",
    factoryReset: "ફેક્ટરી રીસેટ (માસિક)",
    shareBill: "બિલ શેર કરો",
    completeSale: "વેચાણ પૂર્ણ કરો"
  },
  'Hinglish': {
    home: 'Home',
    trends: 'Trends',
    forecast: 'Forecast',
    settings: 'Settings',
    todaysSales: 'Aaj ki Sales',
    orders: 'Orders',
    visits: 'Visits',
    avgBill: 'Avg Bill',
    expenses: 'Kharcha',
    profit: 'Munafa',
    topMovers: 'Top Items',
    needsAttention: 'Dhyan De',
    addSale: 'Sale Jodein',
    addExpense: 'Kharcha Jodein',
    newItem: 'New Item',
    seeAll: 'Sab Dekhein',
    welcome: 'Namaste, Shopkeeper',
    recentActivity: "Aaj ki Activity",
    revenueHistory: "Purani Sales",
    categoryBreakdown: "Category Hisaab",
    peakHours: "Peak Hours",
    aiForecast: "AI Bhavishya",
    poweredBy: "Powered by Gemini",
    predictedProfit: "Aane wala Profit",
    smartAlerts: "Stock Alerts",
    language: "Language",
    lowDataMode: "Low Data Mode",
    backupData: "Backup Data",
    clearData: "Aaj ka data hatayein",
    factoryReset: "Poora Reset karein",
    shareBill: "Bill Bhejein",
    completeSale: "Sale Poori Karein"
  }
};

// START WITH EMPTY DATA FOR FRESH INSTALL
export const MOCK_PRODUCTS: Product[] = [];
export const MOCK_HISTORY: DailyStats[] = [];
export const TODAY_TRANSACTIONS: Transaction[] = [];
export const MOCK_EXPENSES: Expense[] = [];
